### ISSUE TITLE
Add more values from WP_Post?

### ISSUE THREAD

**Issue by timalbert** [Log1x/navi#1]
Hi there - I really appreciate the repo! 

Wondering if you would consider adding `current_item_ancestor` and `current_item_parent` coming from the WP_Post object as values to the object you construct in the parse() method. Currently there is only an `active` value set from WP_Post `current`. 

This would enable more flexibility when building out hierarchical "active" states in navigation menus. I often leverage some of the other items stored in WP_Post too.

Thanks for your consideration

**Comment by Log1x** [comment]
Sure! Any other must-haves?

**Comment by timalbert** [comment]
I find myself using `current`, `current_item_ancestor`, `current_item_parent`, `description` and `target` the most.

**Comment by Log1x** [comment]
#2
