### ISSUE TITLE
Tailwind Active Class

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/navi#10]
Using Tailwind, I'm trying to add an 'active' background class to a parent item (so it shows different class based on the page your currently on), heres what I've tried but not showing a change:

`<li class="inline my-menu-item px-8 active:bg-indigo-400 {{ $item->active ? 'active' : '' }}">`

and also this

`<li class="inline my-menu-item px-8 {{ $item->active ? 'active:bg-indigo-400' : '' }}">`

Any ideas why this may not work?

Thanks.

**Comment by Log1x** [comment]
Wouldn't it just be `{{ $item->active ? 'bg-indigo-400' : '' }}`

**Comment by fabianwurk** [comment]
Spot on exactly. Thanks for quick reply 👌🏻

**Comment by Log1x** [comment]
np
