### ISSUE TITLE
Conflict with Polylang menu language switcher

### ISSUE THREAD

**Issue by uixprt** [Log1x/navi#11]
Hi. very helpful extension.

1. when [Polylang](https://wordpress.org/plugins/polylang/) is activated as the main localization plugin which I preferred. 
2. after added polylang `Language switcher` to the primary navigation rendered by Navi - 
3. and checked the option  `Displays as a dropdown`
4. as a result the site crashed and get into an infinite loop and acquired a fatal error 
`Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 1421312 bytes) in /var/www/html/wp-content/themes/prfwp/vendor/log1x/navi/src/Navi.php on line 97`

![Screenshot from 2019-12-10 18-15-03](https://user-images.githubusercontent.com/6247547/70547951-76202680-1b7a-11ea-9648-e31ba528122f.png)

by the way, in the documentation for Sage10 the line 102 on README.md
`{{ get_field('custom_nav_item_label', $child->object_id) ?: $child->label }}` 
are contain get_field function that should not work without ACF...

Big Thx!

**Comment by Log1x** [comment]
I'll have to take a closer look at this later, but I'm not sure if it is fixable. Looking at Polylang's `PLL_Frontend_Nav_Menu` class – the way they are handling it is a little bizarre to me.

**Edit**: & I updated the README for the ACF example.

**Comment by Log1x** [comment]
I'm closing this as I don't believe there is a possible solution on my part. I'm sorry.
