### ISSUE TITLE
Sage 9 Integration

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/navi#12]
Probably dumb question, I have this working with Sage 10, just wondered what I need to do to get it working with Sage 9. On the docs it shows:

`use Log1x\Navi\Navi;

$navigation = (new Navi())->build('primary_navigation');`

Just wondering where this goes?

Thanks

**Comment by Log1x** [comment]
A controller should suffice.

Just `return (new Navi())->build('primary_navigation');` and go about your business as usual.

**Comment by fabianwurk** [comment]
So I have created a controller under 'app > controllers > navigation.php', and added:

`<?php

namespace App\Controllers;

use Log1x\Navi\Navi;

return (new Navi())->build('primary_navigation');
`
And created my blade partial for this, but still not showing. See attached for ref. Do I have to register the controller somewhere?

<img width="1539" alt="Screenshot 2019-12-17 at 00 49 12" src="https://user-images.githubusercontent.com/18347097/70954977-24d6d200-2067-11ea-84dc-d61a69752c3a.png">

**Comment by Log1x** [comment]
Sage 9's `soberwp/controller` is a little silly and depends on a body class for the Controller to work.

I'd just put it in `app.php`. Navigation is a global thing anyway.

**Comment by fabianwurk** [comment]
Sorry, what code do I add in app.php, and where:

<?php

namespace App\Controllers;

use Sober\Controller\Controller;

class App extends Controller
{
    public static function title()
    {
        if (is_home()) {
            if ($home = get_option('page_for_posts', true)) {
                return get_the_title($home);
            }
            return __('Latest Posts', 'sage');
        }
        if (is_archive()) {
            return get_the_archive_title();
        }
        if (is_search()) {
            return sprintf(__('Search Results for %s', 'sage'), get_search_query());
        }
        if (is_404()) {
            return __('Not Found', 'sage');
        }
        return get_the_title();
    }
}

**Comment by fabianwurk** [comment]
`<?php

namespace App\Controllers;

use Sober\Controller\Controller;

class App extends Controller
{
    public static function title()
    {
        if (is_home()) {
            if ($home = get_option('page_for_posts', true)) {
                return get_the_title($home);
            }
            return __('Latest Posts', 'sage');
        }
        if (is_archive()) {
            return get_the_archive_title();
        }
        if (is_search()) {
            return sprintf(__('Search Results for %s', 'sage'), get_search_query());
        }
        if (is_404()) {
            return __('Not Found', 'sage');
        }
        return get_the_title();
    }
}
`

**Comment by Log1x** [comment]
```php
<?php

namespace App\Controllers;

use Sober\Controller\Controller;
use Log1x\Navi\Navi;

class App extends Controller
{
    public function navigation()
    {
        return (new Navi())->build('primary_navigation');
    }

    public function siteName()
    {
        return get_bloginfo('name');
    }

    public static function title()
    {
        if (is_home()) {
            if ($home = get_option('page_for_posts', true)) {
                return get_the_title($home);
            }
            return __('Latest Posts', 'sage');
        }
        if (is_archive()) {
            return get_the_archive_title();
        }
        if (is_search()) {
            return sprintf(__('Search Results for %s', 'sage'), get_search_query());
        }
        if (is_404()) {
            return __('Not Found', 'sage');
        }
        return get_the_title();
    }
}
```

then use `@foreach ($navigation->toArray() as $item) ... @endforeach` in your view.

**Comment by fabianwurk** [comment]
You're a legend!!! 

Thanks so much, this worked perfectly.

Cheers.

**Comment by Log1x** [comment]
no problem
