### ISSUE TITLE
Post IDs as keys re-sort in Javascript

### ISSUE THREAD

**Issue by tylerwiegand** [Log1x/navi#15]
At first I thought I could solve this with a simple `array_values()`call, and I did for the top level menu items. But when I finally needed to put my children menu items into a vue loop, the key it came away with was the WP_Post ID for the nav item and NOT the order that the menu item is set to.

Order in a PHP Array: 
![image](https://user-images.githubusercontent.com/11890164/74468105-17fc1200-4e4f-11ea-9dc5-2bbb433f0ed7.png)

Order in a Javascript object:
![image](https://user-images.githubusercontent.com/11890164/74468159-35c97700-4e4f-11ea-9bde-797f6353e274.png)

So my first thought was to iterate over the entire menu recursively and do `array_values()` on each children array...but then I was like...thats gross...can't I just set it to an "in order" list in the first place? So I dug around and changed the `tree` function to this:

```php
protected function tree($items, $parent = 0, $branch = [])
    {
        foreach ($items as $key => $item) {
            if ($item->parent == $parent) {
                $children = $this->tree($items, $item->id);
                $item->children = ! empty($children) ? $children : [];

                $branch[$key] = $item;
                unset($item);
            }
        }

        return $branch;
    }
```

I wanted to be able to make this an option but I didn't see any existing "options" like things, and unless the cleanest thing to do is to pass a boolean all the way from the Navi instance like `(new Navi())->build('primary_navigation', true)` and have it end up in the tree function, then I don't have a clean way to implement.

I would almost prefer at this point a better way of doing an `array_values()` on each children item, and maybe just articulating it here will help. 

The closest I got was this  recursive array function, but it just array_values's everything indiscriminately, so theres no useful data afterwards...I tried to get it to only do "children" elements but...no such luck...

```php
// I found this online, I didn't make this up
function array_values_recursive( $array ) {
    $array = array_values( $array );
    for ( $i = 0, $n = count( $array ); $i < $n; $i++ ) {
        $element = $array[$i];
        if ( is_array( $element ) ) {
            $array[$i] = array_values_recursive( $element );
        }
    }
    return $array;
}
```

![image](https://user-images.githubusercontent.com/11890164/74469615-dfaa0300-4e51-11ea-935c-fb6fe67c4b67.png)

**Comment by alwaysblank** [comment]
Maybe I'm misunderstanding (and this is kind of an old question so maybe you figured it out), but couldn't you accomplish this in your template? i.e.:

```blade
@foreach($navi as $item)
  <a data-order="{{ $loop->index }}" href="{{ $item->url }}>{{ $item->label }}</a>
@endforeach
```
Obviously that's per-loop, so if you have nested loops you could get intro trouble, but you could also set a variable and just advance it on every loop iteration to get an uninterrupted series of numbers for your whole menu.
