### ISSUE TITLE
ACF Menu Item on Navi?

### ISSUE THREAD

**Issue by patrickjc** [Log1x/navi#16]
Hi Brandon,

This probably isn't an issue but I have been trying to get ACF Fields displaying on the menu items on Navi - I have tried a few different methods but struggling to get the data appearing.

What is the best way to approach this on Navi?

https://www.advancedcustomfields.com/resources/adding-fields-menu-items/

I am tying to build up a megamenu and have some fields on the menu items to determine dropdown styles.

I have tried your method from docs but this is related the standard ACF page fields rather than the menu item fields I think.

Also have Sage directives and tried with @field but no joy.

Thanks.

**Comment by Log1x** [comment]
I'm terribly sorry for the delayed reply.

You would simply do `{{ get_field('example', $item->id) }}` in your loop.

**Comment by djmtype** [comment]
I'm trying to return ACF field for a menu instead, but I'm getting NULL. Is this not correct? 

```
{{var_dump(get_field('panel_description', $menu))}}
```

Referencing the original ACF docs: https://www.advancedcustomfields.com/resources/adding-fields-menus/

**Comment by Log1x** [comment]
Try `$menu->get()`

**Comment by djmtype** [comment]
Thanks Brandon!
