### ISSUE TITLE
Navi Sage 9 Examples?

### ISSUE THREAD

**Issue by minemindmedia** [Log1x/navi#28]
Hi, I'd love to learn more about how to use this with Sage 9.
Does anyone have an examples or further documentation on how this would be setup with Sage 9?

**Comment by theMosaad** [comment]
You can find some examples in the [Used by section of this repo](https://github.com/Log1x/navi/network/dependents?package_id=UGFja2FnZS01NDI1NzI5NTk%3D) such as [this one](https://github.com/lilianchisca/bfg/tree/master/web/app/themes/bfg)

**Comment by minemindmedia** [comment]
Awesome, thanks for the reply!

**Comment by theMosaad** [comment]
@minemindmedia, even better, @Log1x just added an official example https://github.com/Log1x/navi/tree/master/examples/sage-9
