### ISSUE TITLE
Active Parent if Child isActive

### ISSUE THREAD

**Issue by patrickwurk** [Log1x/navi#29]
Hi Buddy,

Not really an issue but can see in docs for this either - I am trying to get the Parent Item to apply th eactive style if one of the child items is active.

I have partially working with code below but must be doing something wrong.

The last item on the sub nav if active makes the parent active but all other sub nav items dont apply the active to the Parent if that makes sense.

Here is my current code (Tailwind Classes):

`@if ($primary)
<nav id="primary-nav" class="hidden pb-4 md:pb-0 lg:flex lg:justify-end lg:flex-row font-serif z-150">
  <ul>
    @foreach ($primary as $pitem)
      <li class="inline-block relative pl-6 {{ $pitem->classes ?? '' }} {{ $pitem->active ? 'active' : '' }}">
        
        @if ($pitem->children)
          <ul class="z-110 shadow-2xl rounded-lg absolute w-48 bg-white hidden overflow-hidden" style="top: calc(100% + 10px)">
            @foreach ($pitem->children as $child)
              <li class="block bg-none {{ $child->active ? 'active' : '' }}">
                <a href="{{ $child->url }}" class="block py-2 px-3 text-pcol normal-case text-base hover:bg-g-lg hover:text-scol {{ $child->active ? 'text-scol' : '' }}">
                  {{ $child->label }}
                </a>
              </li>
            @endforeach
          </ul>
          @if ($child->active)              
          <a href="{{ $pitem->url }}" class="text-scol hover:text-scol block text-lg p-1 tracking-wide">
            {{ $pitem->label }}
          </a>
          @else
          <a href="{{ $pitem->url }}" class="text-pcol hover:text-scol block text-lg p-1 tracking-wide">
            {{ $pitem->label }}
          </a>
          @endif

        @else
          <a href="{{ $pitem->url }}" class="text-pcol hover:text-scol block text-lg p-1 tracking-wide {{ $pitem->classes ?? '' }} {{ $pitem->active ? 'text-scol border-b-2 border-scol' : '' }}">
            {{ $pitem->label }}
          </a>
        @endif
      </li>
    @endforeach
  </ul>
</nav>
@endif`

**Comment by theMosaad** [comment]
use `$item->activeAncestor`
