### ISSUE TITLE
Nav items with Icons

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/navi#30]
Brandon, is there a way to add different icons beside nav items using Navi (ps. currently using Tailwind so trying to avoid using css pseudo classes). Thanks

**Comment by Log1x** [comment]
If you're using ACF, the easy way would be the just add a menu icon field to the navigation items.

```php
$menu = new FieldsBuilder('menu');

$menu->setLocation('nav_menu_item', '==', 'location/primary_navigation');

$menu->addText('menu_icon');
```

and then in your Navigation blade view loop, you can just `get_field` the menu item ID:

```php
get_field('menu_icon', $item->id)
```

**Comment by fabianwurk** [comment]
Thanks Brandon, but where would I add this block of code in Sage10?

$menu = new FieldsBuilder('menu');



$menu->setLocation('nav_menu_item', '==', 'location/primary_navigation');



$menu->addText('menu_icon');

**Comment by Log1x** [comment]
That was just a dummy example using https://github.com/Log1x/acf-composer

You can add the field however you add field groups (assuming you're using ACF)

**Comment by fabianwurk** [comment]
Ah perfect, I get you. Thanks so much 👍
