### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/navi#38]
Hi Brandon,

I've just installed latest Sage 10 release, and attempting to add back in various navs.

Unfortunately, I'm getting a weird 'Undefined variable' error:

Heres what I have stripped back to just one nav:

Composers > **Navigation.php**:

```
<?php

namespace App\View\Composers;

use Roots\Acorn\View\Composer;
use Log1x\Navi\Facades\Navi;

class Navigation extends Composer
{
    /**
     * @var array
     */
    protected static $views = [
        'partials.header.nav.upper',
    ];

    /**
     * @return array
     */
    public function with()
    {
        return [
            'upper' => $this->upper(),
        ];
    }

    /**
     * @return array
     */
    public function upper()
    {
        if (Navi::build()->isEmpty()) {
            return;
        }

        return Navi::build()->toArray();
    }
}
```
then in **header.blade.php**:

```
        @if ($upper)
          SHOW ME THIS TEXT IF WORKING CORRECTLY
        @endif
```
I've tested the same setup on an older version of Sage 10 and it works as expected.

Any idea why this may be happening on newest release (but I could be doing something stupid 🙈)?

Here is error screen attached.

Thanks

![Screenshot 2021-04-02 at 01 20 00](https://user-images.githubusercontent.com/18347097/113367064-f7dd2a00-9352-11eb-83d0-0b8f67e3fc99.png)

**Comment by Log1x** [comment]
Should your `$views` be set to just `partials.header` ?

**Comment by fabianwurk** [comment]
Have added an extra folder level to segment and manage the partials a bit easier .......

<img width="290" alt="Screenshot 2021-04-02 at 01 37 19" src="https://user-images.githubusercontent.com/18347097/113367480-feb86c80-9353-11eb-827b-01287b03eb59.png">

**Comment by Log1x** [comment]
so it looks like it'd be `partials.header.header` in your current error screenshot? unless you use `$upper` inside of `upper.blade.php` and then `@include` it in your header.

**Comment by fabianwurk** [comment]
Yeah, that was it Brandon. I should've have spotted that 🙈. Many thanks 👍

**Comment by fabianwurk** [comment]
Sorry, back again 🙈 .... I had went and set up all the navs, and I needed to change theme name for repo. When I went back in and restested all, I'm getting errors as per attached depending if I use:

```
    protected static $views = [
        'partials.header.header',
    ];
```
![Screenshot 2021-04-05 at 00 50 21](https://user-images.githubusercontent.com/18347097/113524834-4257e400-95a9-11eb-98b3-a77ef30ed9a8.png)
 
 or
 
 ```
    protected static $views = [
        'partials.header.header.nav',
    ];
```
![Screenshot 2021-04-05 at 00 53 39](https://user-images.githubusercontent.com/18347097/113524851-6ca9a180-95a9-11eb-9ca3-fb41cc901472.png)

Here is current file structure ...

<img width="1672" alt="Screenshot 2021-04-05 at 00 49 41" src="https://user-images.githubusercontent.com/18347097/113524894-a4b0e480-95a9-11eb-9a04-e08ed2634091.png">
 
I've tried many other combinations but all throwing various errors each time.

Any suggestions on where it could be going wrong?

Thanks

**Comment by fabianwurk** [comment]
Repo here if it helps for referencing:

https://github.com/fabianwurk/atomic-jit

**Comment by Log1x** [comment]
so it should be `$views = ['partials.header.nav.upper']` I think?

**Comment by fabianwurk** [comment]
Yeah, had actually tried that too earlier but no joy ...
![Screenshot 2021-04-05 at 02 21 20](https://user-images.githubusercontent.com/18347097/113527539-ca43eb00-95b5-11eb-9287-7d8041f4f8b4.png)

**Comment by Log1x** [comment]
that means its working. your menu is just empty. theres a PR open to fix this from throwing an exception

**Comment by fabianwurk** [comment]
Sorry, confused on this. 

![Screenshot 2021-04-05 at 15 10 20](https://user-images.githubusercontent.com/18347097/113583213-44f62000-9621-11eb-86b4-5af3e2da8e85.png)

The nav is assigned ....

![Screenshot 2021-04-05 at 15 00 50](https://user-images.githubusercontent.com/18347097/113582788-b7b2cb80-9620-11eb-90d7-630e8c2e6a68.png)

but even if I try var dumping the array it just returns error ....

<img width="1650" alt="Screenshot 2021-04-05 at 15 08 54" src="https://user-images.githubusercontent.com/18347097/113582915-dfa22f00-9620-11eb-91fd-f6788b421311.png">

**Comment by fabianwurk** [comment]
I've also changed the file from the PR. It does sort the error, but it's still returning null from var dump of array ...

![Screenshot 2021-04-05 at 15 18 27](https://user-images.githubusercontent.com/18347097/113584025-4aa03580-9622-11eb-8967-73a56bdb8505.png)

**Comment by fabianwurk** [comment]
Repo updated for ref: https://github.com/fabianwurk/atomic-jit

**Comment by fabianwurk** [comment]
@Log1x I've now tested so many configurations of this, and still not working. Also tested this on bare bones fresh install of latest Sage 10 repo. Seems to be an issue where if you change the name of the nav, or add any additional navs, it then fails to show nav. Can you please test this your side to see if you are experiencing same issue? Thanks. 

https://github.com/fabianwurk/atomic-jit

**Comment by Log1x** [comment]
looking into it – not entirely sure what's happening but seems to be an issue with Acorn perhaps. could you try `wp acorn optimize:clear` (or `yarn clean`) after changing everything?

**Comment by fabianwurk** [comment]
I tried `wp acorn optimize:clear`, but no difference unfortunately. FYI ... Works fine with earlier sage 10 branch as I've tested same setup on it so must be some issue with that latest version.

**Comment by Log1x** [comment]
unfortunately I wasn't who did a bulk of the changes in the current master of acorn right now and I've been a little swamped with work – so I'm not entirely sure what got broke and where yet. I know it's not a problem with Navi in particular though but Composers as a whole.

**Comment by Log1x** [comment]
your `config/view.php` or whatever is up to date with the latest master branch of Sage 10? try enabling `globals` in `config/app.php` and see if that makes a difference?

**Comment by fabianwurk** [comment]
Yeah no worries at all. Not a major issue as happy to use earlier version of Sage 10 without Tailwind JIT. Thanks for taking a look anyway👍

**Comment by minemindmedia** [comment]
> looking into it – not entirely sure what's happening but seems to be an issue with Acorn perhaps. could you try `wp acorn optimize:clear` (or `yarn clean`) after changing everything?

This fixed my very similar issue! YAY.
