### ISSUE TITLE
Custom classes excluded

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/navi#41]
Hey @Log1x! 👋🏻   

It seems custom classes added to nav items aren't being added to `$item->classes`.

![Screenshot 2021-04-21 at 17 08 00](https://user-images.githubusercontent.com/1690006/115586177-39af1f80-a2c4-11eb-88b5-797ed299b079.png)

---

Had a quick scan through the code and noticed this is excluding everything except what's in the exclusion list? Unless I'm misreading it.

https://github.com/Log1x/navi/blob/master/src/MenuBuilder.php#L90-L95
```php
$classes = array_filter($item->classes, function ($class) {
    return array_key_exists(
        $class,
        array_flip($this->classes)
    );
});
```

Excluded classes (however they're being allowed). Not sure if this is intentional and simply a typo in the comment:
https://github.com/Log1x/navi/blob/master/src/MenuBuilder.php#L37-L50
```php
/**
  * Blacklisted Classes
  *
  * @var array
  */
protected $classes = [
    'current-menu',
    'current_page',
    'sub-menu',
    'menu-item',
    'menu_item',
    'page-item',
    'page_item',
];
```

I'll try debugging a bit later on and pop a PR over if I can fix, just thought I'd submit this issue in case you know of a solution off the top of your head.

Cheers!

**Comment by jellycode** [comment]
@mike-sheppard I have a pull request in for this issue ( #39 ) already. I couldn't quite figure out what the filter was doing so I just removed it, and everything seems to be working as usual again, but perhaps that isn't the best approach. It got me where I needed to be for the time being at least.

**Comment by mike-sheppard** [comment]
Thanks @jellycode I did see that PR, nice one!  I think the idea behind it is to exclude a bunch of the default nav items class bloat, which I'm all for! I'll pop a PR over shortly that preserves this + custom classes :)

**Comment by kamilgrzegorczyk** [comment]
@Log1x thank you for your effort!

Is there any plan for releasing that anytime soon?

**Comment by Twansparant** [comment]
First of all, thanks for another great package!
I would like to know the same about the classes filter, right now all my custom classes are excluded in the output.
Thanks!

**Comment by kamilgrzegorczyk** [comment]
Hey @Twansparant  - for the time being I switched my projects to install navi as `dev-master` Its an ugly solution but does the job for the time being.

**Comment by Twansparant** [comment]
Hi @kamilgrzegorczyk, thanks that's what I ended up doing too!

**Comment by Log1x** [comment]
release pushed – sorry for the delay.

**Comment by kamilgrzegorczyk** [comment]
Thank you very much @Log1x !
