### ISSUE TITLE
Serious performance issues – just using `build()`, no actual output...

### ISSUE THREAD

**Issue by E-VANCE** [Log1x/navi#57]

**Comment by Log1x** [comment]
Care to elaborate? I've built a few pretty large mega menu's with Navi and have never had any sort of performance issue.

**Comment by E-VANCE** [comment]
Sorry, posted by accident while I was still debugging (hit enter without having added the description) and I found the root issue in the meantime – was calling `(new Navi())->build('primary_navigation')` as a non-static function which resulted in massive overhead / redundancy.

Many thanks for providing this brilliant helper which makes working with the WordPress menus so much cleaner and accessible!

**Comment by Log1x** [comment]
No problem. Glad you got it sorted. 😄
