### ISSUE TITLE
Wrong term slug

### ISSUE THREAD

**Issue by LucasDemea** [Log1x/navi#58]
Hi, thank you for this nice package !
When a menu contains taxonomy terms, the returned slug is not correct :  
![image](https://user-images.githubusercontent.com/22429540/219051428-bb85fd43-9de5-445f-ac83-de2d5651192c.png)

**Comment by Log1x** [comment]
When Navi gives you a parent/slug by default, it typically represents the menu item its self.

You will need to query the `objectId` or `parentObjectId` (if the item is a child) and get the title/slug yourself.
