### ISSUE TITLE
Not compatible with Acorn ^3.0

### ISSUE THREAD

**Issue by matapatos** [Log1x/navi#59]
In Providers/NaviServiceProvider.php the use should be changed from:

`use Roots\Acorn\ServiceProvider;`

To:

`use Roots\Acorn\Sage\SageServiceProvider;`

**Comment by Log1x** [comment]
`Roots\Acorn\ServiceProvider` will probably get removed in a later version of Acorn but it still works as-is.

We wouldn't extend `SageServiceProvider`, but instead `Illuminate\Support\ServiceProvider` directly.
