### ISSUE TITLE
Navi for taxonomy terms

### ISSUE THREAD

**Issue by timalbert** [Log1x/navi#6]
Would it be outside the scope for Navi to build hierarchical WP term objects as well? 

We run into a similar pain point using get_terms or get_categories and it would be awesome to have an object structured the same way for taxonomies.

**Comment by Log1x** [comment]
I'm kind of leaning towards this being something you would just return as an object yourself in a Composer or something. 🤔

The pain-point for navigation is the fact that WordPress doesn't provide any way to return it nested with children alongside requiring an ugly "internal" function [`_wp_menu_item_classes_by_context`](https://github.com/Log1x/navi/blob/master/src/Navi.php#L37) to reinstate classes, attributes, etc. making it kind of an ugly situation compared to just setting it.

It was actually something I had to rack my brain over for quite awhile despite Navi being a rather simple code base.

**Comment by timalbert** [comment]
Yeah that's what we ended up doing. Seems like a repo named Taxi might fit
too :)

--
Tim

**Comment by Log1x** [comment]
Hahaha. It immediately came to mind.
