### ISSUE TITLE
Some kind of message when no menu assigned to location?

### ISSUE THREAD

**Issue by MikeiLL** [Log1x/navi#75]
Hey and thanks for the work.

Would it make sense to have some kind of alert message when the user hasn't yet created a menu?

One inelegant approach would be to add code to `Navi->build()` something like:

```
 if ($menu === 0 || $menu === '' || $menu === null){
    print_r("Log1x\Navi reports: No menu assigned to location. Please assign a menu to location in the WordPress admin panel.");
    die();
 }
```

**Comment by Log1x** [comment]
I feel like with how Navi works, this would be better left to the theme developer to handle whether a menu is required, etc.

**Comment by MikeiLL** [comment]
I see you've also updated the example, `$menu->isNotEmpty()`. Nice!
