### ISSUE TITLE
Class Navi not found

### ISSUE THREAD

**Issue by Coders91** [Log1x/navi#81]
When pushing changes to my dev server I get the fatal error 'Class Navi not found', when using: `@php($menu = Navi::build($name))` it works on my local just fine. I double checked composer but versions are the same, files also all seem to be there. Any ideas?

**Comment by Log1x** [comment]
Perhaps try running `wp acorn optimize:clear` on the dev server? The ability to use `Navi` like that in a view without specifying a namespace comes from loading the Facade, so it's possible there's a cache in place that doesn't have it.

**Comment by Coders91** [comment]
Thanks again Brandon, will keep this command in mind
