### ISSUE TITLE
Docs acorn make:navi 

### ISSUE THREAD

**Issue by huubl** [Log1x/navi#82]
Hi,

The docs mention to run [acorn make:navi](https://github.com/Log1x/navi/blob/d84b4ce2484b0f9a9ee4b0bba2f222f3a03b820a/README.md?plain=1#L65). I had to run this to make it work:

```sh
$ wp acorn package:discover
$ wp acorn make:navi
```

Should `acorn make:navi` work right away, or should the docs be updated?

**Comment by Log1x** [comment]
Assuming the Acorn `post-autoload-dump` composer scripts are installed with `wp acorn acorn:install` and you install Navi alongside Acorn (same `composer.json` file) - you shouldn't have to discover packages.
