### ISSUE TITLE
navi:make not working

### ISSUE THREAD

**Issue by Budolfsen** [Log1x/navi#87]
Just installed this great piece of software to make my own menu in Wordpress with sage  - but I discovered a bug (i think)

I am using version 3.1 - and you should do wp acorn navi:make to create it - but it still uses the old wp acorn make:navi.

Is this not implemented yet or am I doing something wrong.

**Comment by Log1x** [comment]
oops, I forgot to change over the command signature. will update it soon. thanks for the report!
