### ISSUE TITLE
navi:make not working 

### ISSUE THREAD

**Issue by Budolfsen** [Log1x/navi#89]
Hi
I used the version 3.1 where make:navi worked but since you have updated the code and gone to version 3.1.1 to use navi:make I get the following error 

> wp acorn navi:make

   ERROR  There are no commands defined in the "navi" namespace.

If I try to install version 3.1 I can't use the make:navi anymore - just get a error message that it does not exist in the make namespace.

Hope you can help

**Comment by Log1x** [comment]
Try clearing your package cache with `wp acorn optimize:clear` - if that works, you may need to run `wp acorn acorn:install` to add Acorn's `post-autoload-dump` which would handle this automatically.

**Comment by Budolfsen** [comment]
Thanks that did the trick :)
